[project]
name = "research-projects"
version = "0.1.0"
description = "Research projects"
requires-python = ">=3.13"
dependencies = [
    "polars>=1.35.1",
    "pandas>=2.3.3",
    "sympy>=1.14.0",
    "torch>=2.9.0",
    "jax>=0.8.0",
    "transformers>=4.57.1",
    "datasets>=4.3.0",
    "langfuse>=3.8.1",
    "google-cloud-aiplatform>=1.123.0",
    "pydantic>=2.12.3",
    "python-dotenv>=1.2.1",
    "semantic-text-splitter>=0.28.0",
    "sentence-transformers>=5.1.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

[tool.uv.workspace]
members = ["connect4"]
