[project]
name = "research"
version = "0.99"
description = "A collection of research projects."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.11.0",
    "datasets>=4.3.0",
    "e2b-code-interpreter>=2.2.1",
    "evaluate>=0.4.6",
    "google-cloud-aiplatform>=1.123.0",
    "jax>=0.8.0",
    "jupyter>=1.1.1",
    "langfuse>=3.8.1",
    "litellm>=1.79.0",
    "modal>=1.2.1",
    "openai-agents[voice]>=0.4.2",
    "pandas>=2.3.3",
    "polars>=1.35.1",
    "pyaudio>=0.2.14",
    "pydantic>=2.12.3",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "semantic-text-splitter>=0.28.0",
    "sentence-transformers>=5.1.2",
    "smolagents[gradio,litellm]>=1.22.0",
    "sounddevice>=0.5.3",
    "sympy>=1.14.0",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
    "transformers>=4.57.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

