[project]
name = "research-papers"
version = "0.1.0"
description = "Paper implementations"
requires-python = ">=3.13"
dependencies = [
    "torch>=2.9.0",
    "torchvision>=0.24.0",
    "transformers>=4.57.1",
    "datasets>=4.3.0",
    "accelerate>=1.11.0",
    "evaluate>=0.4.6",
    "modal>=1.2.1",
    "pydantic>=2.12.3",
    "python-dotenv>=1.2.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
